name: analysis
permissions: read-all
on: [ push, pull_request ]

env:
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 19 ]
    env:
      JAVA_VERSION: ${{ matrix.java }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
      - name: Run analyzers
        uses: ./.github/actions/run-gradle
        with:
          early-access: false
          java: ${{ matrix.java }}
          arguments: >
            pmdJavaPoet pmdMain pmdCodeGen pmdJmh -Dpmd
            spotbugsJavaPoet spotbugsMain spotbugsCodeGen spotbugsJmh -Dspotbugs
